### ISSUE TITLE
🧪 Replace `pybind11` with `nanobind`

### ISSUE THREAD

**Issue by burgholzer** [cda-tum/mqt-core#344]
Nanobind (https://nanobind.readthedocs.io/en/latest/index.html) is a newer, faster and more lightweight alternative to `pybind11`.
The preferred way to install it (according to the docs) is directly via `pip`, which means fewer submodules for the project here.

There are a couple of things to take care of:
```[tasklist]
### Tasks
- [ ]  A new kind of setup is necessary for building bindings and the corresponding Python package. This is demoed in #359 
- [ ] Switch QCEC to new configuration
- [ ] Switch QMAP to new configuration
- [ ] Switch DDSIM to new configuration
- [ ] Switch QECC to new configuration
- [ ] Switch SyReC to new configuration
```
